### ISSUE TITLE
video play in aws console only for 4 to 5 secs

### ISSUE THREAD

**Issue by awslearne** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#97] opened 2020-05-13 11:38 UTC
Im following code as in 
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/10

Im streaming video from webcam to aws kinesis video.
im using below configuration :
	final CameraMediaSourceConfiguration configuration =
    			new CameraMediaSourceConfiguration.Builder()
    			.withFrameRate(FPS_19)
    			.withRetentionPeriodInHours(1)
    			.withCameraId("video0")
    			.withIsEncoderHardwareAccelerated(false)
    			.withEncodingMimeType("video/avc")
    			.withNalAdaptationFlags(StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_NALS)
    			.withIsAbsoluteTimecode(false)
    			.withEncodingBitRate(200000)//9000000
    			.withHorizontalResolution(640)
    			.withVerticalResolution(480)
    			.withCodecPrivateData(cpd)
    			.build();

but when i view video in aws console playback it show video only for few secs ie around 5 sec with lot of buffering.

How to stream and playback for more than 2 hrs??
Am i doing wrong in bit rate and frame rate??

**Comment by MushMal** [comment] 2020-05-13 16:09
@awslearne it seems that you have an issue on the producer side - could you please include debug logs?

**Comment by awslearne** [comment] 2020-05-14 07:07
please find log attached
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/files/4626577/log.txt)

**Comment by MushMal** [comment] 2020-05-14 23:24
The attached log is just the tail and it shows that your producer is constantly dropping frames

2020-05-14 06:28:30 viewItemRemoved(): Reporting a dropped frame/fragment.

It's observed bandwidth is over 30mbps.

Can you perhaps check the logs as you start - perhaps there is an error that is not included in the tail logs you've attached that can show the root cause

**Comment by MushMal** [comment] 2020-05-20 19:36
Resolving due to staleness. Please feel free to reopen or cut a new one to get further assistance

**Closed by MushMal** 2020-05-20 19:36 UTC
Labels: help wanted, question
