### ISSUE TITLE
Can't find dependent libraries

### ISSUE THREAD

**Issue by sivakrishna0807** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#171] opened 2022-07-28 06:08 UTC
I am running a kinesis video streams producer sdk program on Windows10 using Eclipse IDE. But I am getting an error saying that ERROR com.amazonaws.kinesisvideo.java.client.KinesisVideoJavaClientFactory - Unsatisfied link error. java.lang.UnsatisfiedLinkError: C:\Program Files\Java\jdk-11.0.14\bin\KinesisVideoProducerJNI.dll: Can't find dependent libraries
Exception in thread "main" java.lang.RuntimeException: com.amazonaws.kinesisvideo.producer.ProducerException: Failed loading native library StatusCode: 0xd
	at com.amazonaws.kinesisvideo.demoapp.DemoAppMain.main(DemoAppMain.java:61)
Caused by: com.amazonaws.kinesisvideo.producer.ProducerException: Failed loading native library StatusCode: 0xd

I have added .dll path in kinesis native library and I have no clue of what to do next.

**Comment by disa6302** [comment] 2022-08-01 01:18
Closing this as duplicate of #172

**Closed by disa6302** 2022-08-01 01:18 UTC
